baseurl = "https://micromethodology.com/"
languageCode = "en-us"
title = "Micromethodology"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClassic = false
pygmentsUseClasses = true
PygmentsStyle = "fruity"

[params]
	# General information
	author = "Colm O'Connor"
	description = "The bazaar to scrum/XP/agile's cathedral."
	copyright = "Copyright (C) 2018"

	# Repository
# 	provider = "GitHub"
# 	repo_url = "https://github.com/hitchdev/"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "green"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "hitchdev/micromethodology.com"
	email   = ""

[[menu.main]]
	name   = "Standup"
	url    = "standup/"
	weight = 10

[[menu.main]]
	name   = "Retro"
	url    = "retro/"
	weight = 10

[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
